# Generated by Django 3.0.6 on 2020-06-15 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(max_length=20, verbose_name=['CRITICAL', 'DEBUG', 'ERROR', 'INFO']),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
